// BeeSmart Word Library — 1500+ curated words
// Format: { word, definition, sentence, category, difficulty (1=easy, 2=medium, 3=hard) }

const WORD_LIBRARY = {

  geography: [
    // Easy
    { word: "peninsula", definition: "A piece of land surrounded by water on three sides", sentence: "Spain occupies most of the Iberian ______.", category: "Geography", difficulty: 1 },
    { word: "archipelago", definition: "A group of islands clustered together", sentence: "Indonesia is the world's largest ______, with over 17,000 islands.", category: "Geography", difficulty: 1 },
    { word: "savanna", definition: "A flat grassland in a tropical region", sentence: "Lions roam the African ______ in search of prey.", category: "Geography", difficulty: 1 },
    { word: "plateau", definition: "An area of flat land elevated above surrounding land", sentence: "The Tibetan ______ is the highest in the world.", category: "Geography", difficulty: 1 },
    { word: "fjord", definition: "A narrow inlet of sea between cliffs, formed by glaciers", sentence: "Norway is famous for its dramatic ______ landscapes.", category: "Geography", difficulty: 1 },
    { word: "isthmus", definition: "A narrow strip of land connecting two larger landmasses", sentence: "The ______ of Panama connects North and South America.", category: "Geography", difficulty: 1 },
    { word: "equator", definition: "The imaginary line dividing Earth into northern and southern hemispheres", sentence: "Ecuador sits directly on the ______.", category: "Geography", difficulty: 1 },
    { word: "tundra", definition: "A vast, flat, treeless Arctic region", sentence: "Caribou migrate across the frozen ______ each year.", category: "Geography", difficulty: 1 },
    { word: "canyon", definition: "A deep gorge typically with a river flowing through it", sentence: "The Grand ______ stretches for 277 miles through Arizona.", category: "Geography", difficulty: 1 },
    { word: "glacier", definition: "A slowly moving mass of ice formed from accumulated snow", sentence: "The ______ carved the valley over thousands of years.", category: "Geography", difficulty: 1 },
    { word: "delta", definition: "A landform where a river fans out before entering a larger body of water", sentence: "The Nile ______ is one of the most fertile regions in the world.", category: "Geography", difficulty: 1 },
    { word: "lagoon", definition: "A stretch of salt water separated from the sea by sand or coral", sentence: "The island's ______ was calm and turquoise.", category: "Geography", difficulty: 1 },
    { word: "prairie", definition: "A large open area of grassland in North America", sentence: "Bison once roamed the vast American ______.", category: "Geography", difficulty: 1 },
    { word: "strait", definition: "A narrow passage of water connecting two larger bodies", sentence: "The ______ of Gibraltar separates Europe from Africa.", category: "Geography", difficulty: 1 },
    { word: "oasis", definition: "A fertile spot in a desert where water is found", sentence: "Travelers rested at the ______ after crossing the dunes.", category: "Geography", difficulty: 1 },
    { word: "atoll", definition: "A ring-shaped coral reef enclosing a lagoon", sentence: "The ______ in the Pacific was barely above sea level.", category: "Geography", difficulty: 1 },
    { word: "basin", definition: "A large hollow in the earth's surface, often containing water", sentence: "The Amazon ______ is the world's largest tropical rainforest.", category: "Geography", difficulty: 1 },
    { word: "terrain", definition: "A stretch of land with its natural features", sentence: "The ______ was rocky and difficult to cross on foot.", category: "Geography", difficulty: 1 },
    { word: "latitude", definition: "The angular distance of a place north or south of the equator", sentence: "Higher ______ regions receive less direct sunlight.", category: "Geography", difficulty: 1 },
    // Medium
    { word: "Mediterranean", definition: "The sea surrounded by Europe, Africa, and Asia", sentence: "Greece has thousands of islands in the ______ Sea.", category: "Geography", difficulty: 2 },
    { word: "Mesopotamia", definition: "The ancient region between the Tigris and Euphrates rivers", sentence: "______ is often called the cradle of civilization.", category: "Geography", difficulty: 2 },
    { word: "Appalachian", definition: "A mountain range running along eastern North America", sentence: "The ______ Trail stretches over 2,000 miles.", category: "Geography", difficulty: 2 },
    { word: "Caribbean", definition: "The sea and island region southeast of the Gulf of Mexico", sentence: "Jamaica is a popular ______ vacation destination.", category: "Geography", difficulty: 2 },
    { word: "Himalaya", definition: "The mountain range in Asia containing Earth's highest peaks", sentence: "Mount Everest is part of the ______ range.", category: "Geography", difficulty: 2 },
    { word: "Serengeti", definition: "A vast ecosystem in Tanzania known for wildlife migrations", sentence: "The ______ hosts the world's largest animal migration.", category: "Geography", difficulty: 2 },
    { word: "Mississippi", definition: "The longest river in North America", sentence: "The ______ River flows from Minnesota to the Gulf of Mexico.", category: "Geography", difficulty: 2 },
    { word: "Patagonia", definition: "A sparsely populated region at the southern tip of South America", sentence: "______ is shared between Argentina and Chile.", category: "Geography", difficulty: 2 },
    { word: "Polynesia", definition: "A subregion of Oceania made up of over 1,000 islands", sentence: "Hawaii is part of the ______ triangle.", category: "Geography", difficulty: 2 },
    { word: "Sahara", definition: "The world's largest hot desert, located in North Africa", sentence: "The ______ covers much of northern Africa.", category: "Geography", difficulty: 2 },
    { word: "Scandinavia", definition: "A region of Northern Europe comprising Norway, Sweden, and Denmark", sentence: "______ is known for its fjords and Viking history.", category: "Geography", difficulty: 2 },
    { word: "Caucasus", definition: "A region between the Black and Caspian seas", sentence: "The ______ Mountains form a natural border between Europe and Asia.", category: "Geography", difficulty: 2 },
    { word: "Sahel", definition: "The semi-arid transition zone south of the Sahara", sentence: "The ______ region faces severe drought and desertification.", category: "Geography", difficulty: 2 },
    { word: "Anatolia", definition: "The peninsula of land that forms the Asian portion of Turkey", sentence: "______ has been home to many great civilizations.", category: "Geography", difficulty: 2 },
    { word: "Siberia", definition: "A vast region of Russia spanning from the Urals to the Pacific", sentence: "______ contains some of the coldest inhabited places on Earth.", category: "Geography", difficulty: 2 },
    { word: "Euphrates", definition: "One of the two great rivers of ancient Mesopotamia", sentence: "The ______ River flows through Syria and Iraq.", category: "Geography", difficulty: 2 },
    { word: "Pyrenees", definition: "The mountain range forming the border between France and Spain", sentence: "The ______ stretch from the Atlantic to the Mediterranean.", category: "Geography", difficulty: 2 },
    // Hard
    { word: "Kyrgyzstan", definition: "A landlocked country in Central Asia", sentence: "______ is known for its mountainous terrain and nomadic culture.", category: "Geography", difficulty: 3 },
    { word: "Ouagadougou", definition: "The capital city of Burkina Faso in West Africa", sentence: "______ is one of the largest cities in West Africa.", category: "Geography", difficulty: 3 },
    { word: "Djibouti", definition: "A small country on the Horn of Africa", sentence: "______ sits at a strategic point on the Red Sea.", category: "Geography", difficulty: 3 },
    { word: "Liechtenstein", definition: "A tiny landlocked country between Switzerland and Austria", sentence: "______ is one of only two doubly landlocked countries.", category: "Geography", difficulty: 3 },
    { word: "Azerbaijan", definition: "A country at the crossroads of Eastern Europe and Western Asia", sentence: "______ borders the Caspian Sea to the east.", category: "Geography", difficulty: 3 },
    { word: "Mozambique", definition: "A country in southeastern Africa", sentence: "______ has a long coastline along the Indian Ocean.", category: "Geography", difficulty: 3 },
    { word: "Tajikistan", definition: "A mountainous landlocked country in Central Asia", sentence: "______ is the smallest country in Central Asia by area.", category: "Geography", difficulty: 3 },
    { word: "Turkmenistan", definition: "A Central Asian country bordering the Caspian Sea", sentence: "______ has one of the world's largest natural gas reserves.", category: "Geography", difficulty: 3 },
    { word: "Seychelles", definition: "An island nation in the Indian Ocean northeast of Madagascar", sentence: "______ is known for its pristine beaches and coral reefs.", category: "Geography", difficulty: 3 },
    { word: "Kiribati", definition: "A Pacific island nation straddling the equator and international date line", sentence: "______ is one of the first countries threatened by rising seas.", category: "Geography", difficulty: 3 },
    { word: "Comoros", definition: "An island nation off the eastern coast of Africa", sentence: "The ______ islands are located in the Indian Ocean.", category: "Geography", difficulty: 3 },
  ],

  history: [
    // Easy
    { word: "pharaoh", definition: "A ruler of ancient Egypt", sentence: "The ______ ordered the construction of the great pyramid.", category: "People & History", difficulty: 1 },
    { word: "emperor", definition: "A sovereign ruler of an empire", sentence: "The ______ commanded armies across three continents.", category: "People & History", difficulty: 1 },
    { word: "medieval", definition: "Relating to the Middle Ages, roughly 500-1500 AD", sentence: "The ______ castle was built to withstand sieges.", category: "People & History", difficulty: 1 },
    { word: "democracy", definition: "A system of government by the whole population", sentence: "Ancient Athens is considered the birthplace of ______.", category: "People & History", difficulty: 1 },
    { word: "revolution", definition: "A forcible overthrow of a government or social order", sentence: "The French ______ began in 1789.", category: "People & History", difficulty: 1 },
    { word: "constitution", definition: "A body of fundamental principles governing a state", sentence: "The American ______ was ratified in 1788.", category: "People & History", difficulty: 1 },
    { word: "feudalism", definition: "The dominant social system in medieval Europe", sentence: "Under ______, peasants worked land owned by lords.", category: "People & History", difficulty: 1 },
    { word: "gladiator", definition: "A trained fighter in ancient Roman public spectacles", sentence: "The ______ fought before thousands in the Colosseum.", category: "People & History", difficulty: 1 },
    { word: "monarchy", definition: "A form of government with a monarch as head of state", sentence: "Britain has maintained a constitutional ______ for centuries.", category: "People & History", difficulty: 1 },
    { word: "renaissance", definition: "The cultural rebirth of Europe from the 14th to 17th century", sentence: "Leonardo da Vinci was the ultimate ______ man.", category: "People & History", difficulty: 1 },
    { word: "parliament", definition: "A legislative body of government", sentence: "The British ______ is one of the oldest in the world.", category: "People & History", difficulty: 1 },
    { word: "dynasty", definition: "A line of hereditary rulers of a country", sentence: "The Ming ______ ruled China for nearly 300 years.", category: "People & History", difficulty: 1 },
    { word: "cavalry", definition: "Soldiers who fight on horseback", sentence: "The ______ charged across the battlefield at dawn.", category: "People & History", difficulty: 1 },
    { word: "republic", definition: "A state governed by elected representatives", sentence: "Rome transitioned from a kingdom to a ______ in 509 BC.", category: "People & History", difficulty: 1 },
    { word: "crusade", definition: "A medieval military expedition by Christians to recover the Holy Land", sentence: "The First ______ captured Jerusalem in 1099.", category: "People & History", difficulty: 1 },
    // Medium
    { word: "Charlemagne", definition: "The King of the Franks who united much of Western Europe", sentence: "______ was crowned Holy Roman Emperor in 800 AD.", category: "People & History", difficulty: 2 },
    { word: "Enlightenment", definition: "An 18th-century intellectual movement emphasizing reason", sentence: "The ______ laid the groundwork for modern democracy.", category: "People & History", difficulty: 2 },
    { word: "Reformation", definition: "The 16th-century movement that split Western Christianity", sentence: "Martin Luther sparked the Protestant ______ in 1517.", category: "People & History", difficulty: 2 },
    { word: "Napoleonic", definition: "Relating to Napoleon Bonaparte or his era", sentence: "The ______ Wars reshaped the map of Europe.", category: "People & History", difficulty: 2 },
    { word: "suffragette", definition: "A woman who campaigned for the right to vote", sentence: "The ______ chained herself to the railings in protest.", category: "People & History", difficulty: 2 },
    { word: "Versailles", definition: "The French royal palace and site of a major WWI peace treaty", sentence: "The Treaty of ______ officially ended World War I.", category: "People & History", difficulty: 2 },
    { word: "inquisition", definition: "A medieval Catholic tribunal for suppressing heresy", sentence: "The Spanish ______ was feared across the Iberian Peninsula.", category: "People & History", difficulty: 2 },
    { word: "Ottoman", definition: "Relating to the Turkish empire that lasted from 1299 to 1922", sentence: "The ______ Empire controlled vast territories across three continents.", category: "People & History", difficulty: 2 },
    { word: "Byzantine", definition: "Relating to the Eastern Roman Empire centered in Constantinople", sentence: "The ______ Empire preserved Roman culture for a thousand years.", category: "People & History", difficulty: 2 },
    { word: "Prohibition", definition: "The period from 1920 to 1933 when alcohol was banned in the US", sentence: "______ gave rise to speakeasies and organized crime.", category: "People & History", difficulty: 2 },
    { word: "imperialism", definition: "A policy of extending a country's power through colonization", sentence: "British ______ spread across Africa and Asia in the 19th century.", category: "People & History", difficulty: 2 },
    { word: "propaganda", definition: "Information used to promote a particular political cause", sentence: "The wartime ______ posters urged citizens to enlist.", category: "People & History", difficulty: 2 },
    // Hard
    { word: "Robespierre", definition: "A radical leader of the French Revolution's Reign of Terror", sentence: "______ was eventually guillotined by his own revolutionary allies.", category: "People & History", difficulty: 3 },
    { word: "Zoroastrianism", definition: "One of the world's oldest monotheistic religions, founded in Persia", sentence: "______ influenced Judaism, Christianity, and Islam.", category: "People & History", difficulty: 3 },
    { word: "Thermopylae", definition: "The ancient Greek pass where 300 Spartans made a famous stand", sentence: "The Battle of ______ became a symbol of heroic sacrifice.", category: "People & History", difficulty: 3 },
    { word: "Conquistador", definition: "A Spanish conqueror of the Americas in the 16th century", sentence: "The ______ claimed vast territories for the Spanish crown.", category: "People & History", difficulty: 3 },
    { word: "Bolshevik", definition: "A member of the radical Russian socialist party that seized power in 1917", sentence: "The ______ Revolution transformed Russia into a communist state.", category: "People & History", difficulty: 3 },
    { word: "Rasputin", definition: "A controversial mystic who influenced the Russian royal family", sentence: "______ gained extraordinary influence over Tsar Nicholas II's court.", category: "People & History", difficulty: 3 },
    { word: "Hammurabi", definition: "The Babylonian king who created one of the earliest written law codes", sentence: "______ established that the punishment should fit the crime.", category: "People & History", difficulty: 3 },
    { word: "Conquistador", definition: "A Spanish conqueror of the Americas in the 16th century", sentence: "The ______ claimed vast territories for the Spanish crown.", category: "People & History", difficulty: 3 },
    { word: "Suleiman", definition: "The Ottoman sultan known as the Magnificent who ruled 1520-1566", sentence: "______ expanded the Ottoman Empire to its greatest extent.", category: "People & History", difficulty: 3 },
    { word: "Richelieu", definition: "The powerful French cardinal who served Louis XIII", sentence: "Cardinal ______ centralized power in the French monarchy.", category: "People & History", difficulty: 3 },
  ],

  science: [
    // Easy
    { word: "nucleus", definition: "The central part of an atom or cell", sentence: "The ______ of an atom contains protons and neutrons.", category: "Science & Nature", difficulty: 1 },
    { word: "photosynthesis", definition: "The process plants use to convert sunlight into food", sentence: "Without ______, plants could not produce their own energy.", category: "Science & Nature", difficulty: 1 },
    { word: "atmosphere", definition: "The layer of gases surrounding a planet", sentence: "Earth's ______ protects us from harmful solar radiation.", category: "Science & Nature", difficulty: 1 },
    { word: "hibernation", definition: "A dormant state some animals enter during winter", sentence: "Bears enter ______ to survive the cold winter months.", category: "Science & Nature", difficulty: 1 },
    { word: "evaporation", definition: "The process of liquid turning into vapor", sentence: "______ causes puddles to disappear on a sunny day.", category: "Science & Nature", difficulty: 1 },
    { word: "ecosystem", definition: "A community of living organisms in their environment", sentence: "The coral reef ______ supports thousands of species.", category: "Science & Nature", difficulty: 1 },
    { word: "vertebrate", definition: "An animal with a backbone or spinal column", sentence: "Fish, birds, and mammals are all ______s.", category: "Science & Nature", difficulty: 1 },
    { word: "metamorphosis", definition: "The process of transformation in an organism's life cycle", sentence: "A caterpillar undergoes ______ to become a butterfly.", category: "Science & Nature", difficulty: 1 },
    { word: "gravity", definition: "The force that attracts objects toward one another", sentence: "______ keeps the planets in orbit around the sun.", category: "Science & Nature", difficulty: 1 },
    { word: "erosion", definition: "The gradual wearing away of rock or soil by water, wind, or ice", sentence: "______ carved the Grand Canyon over millions of years.", category: "Science & Nature", difficulty: 1 },
    { word: "bacteria", definition: "Single-celled microorganisms found in every environment", sentence: "Some ______ are beneficial while others cause disease.", category: "Science & Nature", difficulty: 1 },
    { word: "predator", definition: "An animal that hunts and eats other animals", sentence: "The cheetah is the fastest land ______.", category: "Science & Nature", difficulty: 1 },
    { word: "fossil", definition: "The preserved remains of a prehistoric organism", sentence: "The dinosaur ______ was discovered in a remote desert.", category: "Science & Nature", difficulty: 1 },
    { word: "migration", definition: "The seasonal movement of animals from one region to another", sentence: "The monarch butterfly's annual ______ spans thousands of miles.", category: "Science & Nature", difficulty: 1 },
    // Medium
    { word: "mitochondria", definition: "The organelle that produces energy in cells", sentence: "The ______ is often called the powerhouse of the cell.", category: "Science & Nature", difficulty: 2 },
    { word: "tectonic", definition: "Relating to the structure and movement of Earth's crust", sentence: "______ plate movement causes earthquakes and volcanoes.", category: "Science & Nature", difficulty: 2 },
    { word: "symbiosis", definition: "A close interaction between two different organisms", sentence: "Clownfish and sea anemones live in ______.", category: "Science & Nature", difficulty: 2 },
    { word: "electromagnetic", definition: "Relating to the interaction of electric and magnetic fields", sentence: "Visible light is part of the ______ spectrum.", category: "Science & Nature", difficulty: 2 },
    { word: "hypothesis", definition: "A proposed explanation made as a starting point for investigation", sentence: "The scientist tested her ______ with a controlled experiment.", category: "Science & Nature", difficulty: 2 },
    { word: "bioluminescence", definition: "The production of light by living organisms", sentence: "Deep sea fish use ______ to attract prey in the dark.", category: "Science & Nature", difficulty: 2 },
    { word: "relativity", definition: "Einstein's theory describing the relationship between space, time, and gravity", sentence: "Einstein's theory of ______ changed our understanding of physics.", category: "Science & Nature", difficulty: 2 },
    { word: "taxonomy", definition: "The classification of organisms into groups", sentence: "Carl Linnaeus developed the system of biological ______.", category: "Science & Nature", difficulty: 2 },
    { word: "osmosis", definition: "The movement of water through a membrane from low to high concentration", sentence: "Plant roots absorb water through ______.", category: "Science & Nature", difficulty: 2 },
    { word: "antibiotic", definition: "A medicine that kills or inhibits bacterial growth", sentence: "Penicillin was the world's first ______.", category: "Science & Nature", difficulty: 2 },
    { word: "supernova", definition: "A stellar explosion that briefly outshines an entire galaxy", sentence: "A ______ can release more energy than the sun will in its lifetime.", category: "Science & Nature", difficulty: 2 },
    { word: "Pangaea", definition: "The supercontinent that existed before it broke apart", sentence: "______ began splitting apart about 175 million years ago.", category: "Science & Nature", difficulty: 2 },
    { word: "catalyst", definition: "A substance that speeds up a chemical reaction without being consumed", sentence: "Enzymes act as biological ______s in the body.", category: "Science & Nature", difficulty: 2 },
    // Hard
    { word: "thermodynamics", definition: "The branch of physics dealing with heat and energy", sentence: "The laws of ______ govern how energy moves through systems.", category: "Science & Nature", difficulty: 3 },
    { word: "photovoltaic", definition: "Relating to the production of electricity from light", sentence: "______ cells convert sunlight directly into electricity.", category: "Science & Nature", difficulty: 3 },
    { word: "cephalopod", definition: "A class of mollusks including squid, octopus, and nautilus", sentence: "The octopus is the most intelligent ______.", category: "Science & Nature", difficulty: 3 },
    { word: "perihelion", definition: "The point in a planet's orbit closest to the sun", sentence: "Earth reaches its ______ in early January.", category: "Science & Nature", difficulty: 3 },
    { word: "telomere", definition: "A protective cap at the end of a chromosome", sentence: "Shortened ______s are associated with aging and disease.", category: "Science & Nature", difficulty: 3 },
    { word: "quasar", definition: "An extremely luminous active galactic nucleus", sentence: "A ______ can outshine an entire galaxy of stars.", category: "Science & Nature", difficulty: 3 },
    { word: "mycorrhizal", definition: "Relating to the symbiotic relationship between fungi and plant roots", sentence: "______ networks allow trees to share nutrients underground.", category: "Science & Nature", difficulty: 3 },
    { word: "spectrometry", definition: "The measurement of spectra produced when matter interact with energy", sentence: "Mass ______ can identify unknown chemical compounds.", category: "Science & Nature", difficulty: 3 },
    { word: "singularity", definition: "A point in space-time where density becomes infinite", sentence: "A black hole's ______ defies all known physics.", category: "Science & Nature", difficulty: 3 },
    { word: "exoplanet", definition: "A planet orbiting a star outside our solar system", sentence: "Thousands of ______s have been discovered by space telescopes.", category: "Science & Nature", difficulty: 3 },
  ],

  arts: [
    // Easy
    { word: "symphony", definition: "An elaborate musical composition for a full orchestra", sentence: "Beethoven's Ninth ______ is among the greatest ever written.", category: "Arts & Culture", difficulty: 1 },
    { word: "sculpture", definition: "The art of making three-dimensional forms", sentence: "Michelangelo's ______ of David stands in Florence.", category: "Arts & Culture", difficulty: 1 },
    { word: "baroque", definition: "A highly ornate style of art and architecture from the 17th century", sentence: "The ______ style featured elaborate decoration and drama.", category: "Arts & Culture", difficulty: 1 },
    { word: "sonnet", definition: "A poem of 14 lines with a specific rhyme scheme", sentence: "Shakespeare wrote 154 ______s during his lifetime.", category: "Arts & Culture", difficulty: 1 },
    { word: "impressionism", definition: "An art movement capturing fleeting impressions through loose brushwork", sentence: "Monet pioneered the ______ movement in 19th-century France.", category: "Arts & Culture", difficulty: 1 },
    { word: "choreography", definition: "The art of designing and arranging dance sequences", sentence: "The ______ for Swan Lake is among the most demanding in ballet.", category: "Arts & Culture", difficulty: 1 },
    { word: "narrative", definition: "A spoken or written account of connected events", sentence: "The film's ______ jumped between past and present.", category: "Arts & Culture", difficulty: 1 },
    { word: "allegory", definition: "A story with a hidden symbolic meaning", sentence: "Orwell's Animal Farm is a political ______.", category: "Arts & Culture", difficulty: 1 },
    { word: "fresco", definition: "A technique of painting on wet plaster", sentence: "The ______ on the ceiling had survived for centuries.", category: "Arts & Culture", difficulty: 1 },
    { word: "ceramics", definition: "The art of making objects from clay fired at high temperatures", sentence: "Ancient Greek ______ depicted scenes from mythology.", category: "Arts & Culture", difficulty: 1 },
    // Medium
    { word: "chiaroscuro", definition: "The use of strong contrasts of light and dark in art", sentence: "Caravaggio was a master of ______ technique.", category: "Arts & Culture", difficulty: 2 },
    { word: "cubism", definition: "An art movement depicting subjects from multiple viewpoints simultaneously", sentence: "Picasso and Braque developed ______ in the early 20th century.", category: "Arts & Culture", difficulty: 2 },
    { word: "soliloquy", definition: "A speech in a play where a character speaks thoughts aloud alone", sentence: "Hamlet's famous ______ begins with 'To be or not to be'.", category: "Arts & Culture", difficulty: 2 },
    { word: "surrealism", definition: "An art movement combining realistic imagery with dreamlike elements", sentence: "Salvador Dali's melting clocks are icons of ______.", category: "Arts & Culture", difficulty: 2 },
    { word: "Beethoven", definition: "The German composer who wrote nine symphonies while deaf", sentence: "______ completed his Ninth Symphony after losing his hearing.", category: "Arts & Culture", difficulty: 2 },
    { word: "protagonist", definition: "The main character in a literary work", sentence: "The ______ struggles against overwhelming odds throughout the novel.", category: "Arts & Culture", difficulty: 2 },
    { word: "Michelangelo", definition: "The Italian Renaissance artist who painted the Sistine Chapel ceiling", sentence: "______ spent four years painting the Sistine Chapel ceiling.", category: "Arts & Culture", difficulty: 2 },
    { word: "Tchaikovsky", definition: "The Russian composer who wrote Swan Lake and The Nutcracker", sentence: "______ composed some of the most beloved ballet scores ever written.", category: "Arts & Culture", difficulty: 2 },
    { word: "expressionism", definition: "An art movement seeking to express emotional experience rather than physical reality", sentence: "Munch's The Scream is the defining image of ______.", category: "Arts & Culture", difficulty: 2 },
    { word: "Dostoevsky", definition: "The Russian novelist who wrote Crime and Punishment", sentence: "______ explored the psychology of guilt and redemption.", category: "Arts & Culture", difficulty: 2 },
    { word: "Rembrandt", definition: "The Dutch master known for his self-portraits and use of light", sentence: "______ painted over 90 self-portraits during his career.", category: "Arts & Culture", difficulty: 2 },
    { word: "Tolstoy", definition: "The Russian author of War and Peace", sentence: "______ wrote some of the longest novels in literary history.", category: "Arts & Culture", difficulty: 2 },
    // Hard
    { word: "Scheherazade", definition: "The fictional storyteller of One Thousand and One Nights", sentence: "______ told stories each night to delay her execution.", category: "Arts & Culture", difficulty: 3 },
    { word: "Stravinsky", definition: "The Russian composer whose Rite of Spring caused a famous riot", sentence: "______ transformed 20th-century music with his radical compositions.", category: "Arts & Culture", difficulty: 3 },
    { word: "Bauhaus", definition: "A German school of art and design combining fine art with craft", sentence: "The ______ movement influenced modern architecture and design.", category: "Arts & Culture", difficulty: 3 },
    { word: "Cervantes", definition: "The Spanish author of Don Quixote", sentence: "______ wrote what many consider the first modern novel.", category: "Arts & Culture", difficulty: 3 },
    { word: "Rachmaninoff", definition: "A Russian composer and pianist known for his piano concertos", sentence: "______ is considered one of the greatest pianists of his era.", category: "Arts & Culture", difficulty: 3 },
    { word: "Caravaggio", definition: "The Italian Baroque painter known for dramatic use of light", sentence: "______ revolutionized painting with his raw, realistic style.", category: "Arts & Culture", difficulty: 3 },
    { word: "contrapuntal", definition: "Relating to counterpoint in music, where melodies interweave", sentence: "Bach's fugues are masterpieces of ______ composition.", category: "Arts & Culture", difficulty: 3 },
  ],

  food: [
    // Easy
    { word: "blanch", definition: "To briefly boil food then plunge it into cold water", sentence: "She would ______ the green beans before freezing them.", category: "Food & Cooking", difficulty: 1 },
    { word: "simmer", definition: "To cook just below boiling point", sentence: "Let the soup ______ for twenty minutes before serving.", category: "Food & Cooking", difficulty: 1 },
    { word: "marinade", definition: "A sauce used to soak food before cooking", sentence: "The chicken sat in a ______ of lemon and herbs overnight.", category: "Food & Cooking", difficulty: 1 },
    { word: "garnish", definition: "A decorative or flavorful addition to a finished dish", sentence: "A sprig of parsley served as the perfect ______.", category: "Food & Cooking", difficulty: 1 },
    { word: "fermentation", definition: "The chemical breakdown of food by microorganisms", sentence: "______ is what transforms grapes into wine.", category: "Food & Cooking", difficulty: 1 },
    { word: "vinaigrette", definition: "A salad dressing made of oil and vinegar", sentence: "She tossed the salad in a light lemon ______.", category: "Food & Cooking", difficulty: 1 },
    { word: "julienne", definition: "To cut food into thin matchstick-sized strips", sentence: "______ the carrots into thin strips for the stir-fry.", category: "Food & Cooking", difficulty: 1 },
    { word: "emulsify", definition: "To combine two liquids that normally do not mix", sentence: "Whisk vigorously to ______ the oil and vinegar.", category: "Food & Cooking", difficulty: 1 },
    { word: "caramelize", definition: "To heat sugar until it melts and turns golden brown", sentence: "______ the onions slowly over low heat for best flavor.", category: "Food & Cooking", difficulty: 1 },
    { word: "braise", definition: "To cook meat slowly in a small amount of liquid", sentence: "______ the short ribs for three hours until tender.", category: "Food & Cooking", difficulty: 1 },
    { word: "puree", definition: "To blend food into a smooth, creamy paste", sentence: "______ the roasted tomatoes into a silky sauce.", category: "Food & Cooking", difficulty: 1 },
    // Medium
    { word: "charcuterie", definition: "A branch of cooking devoted to prepared meat products", sentence: "The ______ board was loaded with cured meats and cheeses.", category: "Food & Cooking", difficulty: 2 },
    { word: "consomme", definition: "A clear soup made from clarified meat or fish stock", sentence: "The chef strained the ______ until it was perfectly clear.", category: "Food & Cooking", difficulty: 2 },
    { word: "prosciutto", definition: "Italian dry-cured ham typically served thinly sliced", sentence: "The melon was wrapped in thin slices of ______.", category: "Food & Cooking", difficulty: 2 },
    { word: "Worcestershire", definition: "A fermented liquid condiment originating from Worcester, England", sentence: "A dash of ______ sauce adds depth to a Bloody Mary.", category: "Food & Cooking", difficulty: 2 },
    { word: "ratatouille", definition: "A French Provencal stewed vegetable dish", sentence: "She made a colorful ______ with summer vegetables from the garden.", category: "Food & Cooking", difficulty: 2 },
    { word: "bruschetta", definition: "Grilled bread rubbed with garlic and topped with ingredients", sentence: "The ______ was topped with fresh tomatoes and basil.", category: "Food & Cooking", difficulty: 2 },
    { word: "gnocchi", definition: "Italian dumplings made from potato, flour, and egg", sentence: "The ______ were light and pillowy, tossed in sage butter.", category: "Food & Cooking", difficulty: 2 },
    { word: "bechamel", definition: "A white sauce made from butter, flour, and milk", sentence: "The lasagna was layered with ______ and bolognese.", category: "Food & Cooking", difficulty: 2 },
    { word: "gazpacho", definition: "A cold Spanish soup made from raw blended vegetables", sentence: "She served chilled ______ on a hot summer evening.", category: "Food & Cooking", difficulty: 2 },
    { word: "risotto", definition: "A creamy Italian rice dish cooked with broth", sentence: "The mushroom ______ took thirty minutes of constant stirring.", category: "Food & Cooking", difficulty: 2 },
    { word: "souffle", definition: "A light baked dish made fluffy with egg whites", sentence: "The chocolate ______ collapsed moments after leaving the oven.", category: "Food & Cooking", difficulty: 2 },
    // Hard
    { word: "amuse-bouche", definition: "A single bite-sized appetizer offered before a meal", sentence: "The chef sent out an ______ of caviar on creme fraiche.", category: "Food & Cooking", difficulty: 3 },
    { word: "mirepoix", definition: "A mixture of diced onion, carrot, and celery used as a flavor base", sentence: "Every good stock begins with a ______ of aromatic vegetables.", category: "Food & Cooking", difficulty: 3 },
    { word: "chiffonade", definition: "Thin ribbon-like strips of herbs or leafy vegetables", sentence: "A ______ of fresh basil decorated the finished pasta.", category: "Food & Cooking", difficulty: 3 },
    { word: "umami", definition: "A savory taste considered the fifth basic flavor", sentence: "Parmesan and mushrooms are both rich sources of ______.", category: "Food & Cooking", difficulty: 3 },
    { word: "bourguignon", definition: "A French stew braised in red Burgundy wine", sentence: "Boeuf ______ is a classic French comfort dish.", category: "Food & Cooking", difficulty: 3 },
    { word: "gastrique", definition: "A sweet and sour sauce made from caramelized sugar and vinegar", sentence: "A raspberry ______ balanced the richness of the duck.", category: "Food & Cooking", difficulty: 3 },
    { word: "veloute", definition: "One of the five French mother sauces made from light stock", sentence: "The ______ was thickened with a blond roux.", category: "Food & Cooking", difficulty: 3 },
  ],

  general: [
    // Easy
    { word: "necessary", definition: "Required to be done or achieved", sentence: "It is ______ to practice every day to improve.", category: "General", difficulty: 1 },
    { word: "accommodate", definition: "To provide lodging or space for", sentence: "The hotel could ______ up to 500 guests.", category: "General", difficulty: 1 },
    { word: "occurrence", definition: "An incident or event", sentence: "Seeing a double rainbow is a rare ______.", category: "General", difficulty: 1 },
    { word: "conscience", definition: "An inner sense of right and wrong", sentence: "His ______ prevented him from lying.", category: "General", difficulty: 1 },
    { word: "rhythm", definition: "A strong, regular, repeated pattern of sound or movement", sentence: "The drummer kept a steady ______ throughout the song.", category: "General", difficulty: 1 },
    { word: "privilege", definition: "A special right or advantage available only to certain people", sentence: "Access to clean water is a ______ not everyone has.", category: "General", difficulty: 1 },
    { word: "exaggerate", definition: "To represent something as greater than it really is", sentence: "He tended to ______ the size of the fish he caught.", category: "General", difficulty: 1 },
    { word: "guarantee", definition: "A formal promise or assurance", sentence: "The manufacturer offers a five-year ______.", category: "General", difficulty: 1 },
    { word: "separate", definition: "To move or come apart", sentence: "______ the egg whites from the yolks carefully.", category: "General", difficulty: 1 },
    { word: "embarrass", definition: "To cause someone to feel awkward or ashamed", sentence: "She did not want to ______ him in front of his friends.", category: "General", difficulty: 1 },
    { word: "recommend", definition: "To put forward with approval", sentence: "I would ______ the salmon — it's excellent tonight.", category: "General", difficulty: 1 },
    { word: "colleague", definition: "A person with whom one works", sentence: "She introduced me to her ______ from the London office.", category: "General", difficulty: 1 },
    { word: "perceive", definition: "To become aware of something through the senses", sentence: "We ______ color differently depending on lighting conditions.", category: "General", difficulty: 1 },
    { word: "sufficient", definition: "Enough; adequate for the purpose", sentence: "One coat of paint was not ______ to cover the dark wall.", category: "General", difficulty: 1 },
    // Medium
    { word: "bureaucracy", definition: "A system of government with complex rules and procedures", sentence: "Navigating the ______ took months of paperwork.", category: "General", difficulty: 2 },
    { word: "conscientious", definition: "Wishing to do what is right; diligent and thorough", sentence: "She was a ______ worker who never missed a detail.", category: "General", difficulty: 2 },
    { word: "paraphernalia", definition: "Miscellaneous articles or equipment", sentence: "He arrived with all the ______ of a serious photographer.", category: "General", difficulty: 2 },
    { word: "idiosyncrasy", definition: "A distinctive or peculiar feature of a person", sentence: "His habit of humming while reading was an endearing ______.", category: "General", difficulty: 2 },
    { word: "serendipity", definition: "The occurrence of events by chance in a happy way", sentence: "Finding that old friend was pure ______.", category: "General", difficulty: 2 },
    { word: "onomatopoeia", definition: "A word that phonetically imitates the sound it describes", sentence: "Words like buzz and crash are examples of ______.", category: "General", difficulty: 2 },
    { word: "benevolent", definition: "Well-meaning and kindly", sentence: "The ______ donor funded the entire scholarship program.", category: "General", difficulty: 2 },
    { word: "perseverance", definition: "Continued effort despite difficulty or delay", sentence: "Her ______ eventually paid off after years of practice.", category: "General", difficulty: 2 },
    { word: "acquiesce", definition: "To accept something reluctantly but without protest", sentence: "He chose to ______ rather than start an argument.", category: "General", difficulty: 2 },
    { word: "quintessential", definition: "Representing the most perfect example of something", sentence: "The film is the ______ road trip movie.", category: "General", difficulty: 2 },
    { word: "meticulous", definition: "Showing great attention to detail", sentence: "The ______ researcher checked every footnote twice.", category: "General", difficulty: 2 },
    { word: "facetious", definition: "Treating serious issues with inappropriate humor", sentence: "His ______ comment was poorly timed given the situation.", category: "General", difficulty: 2 },
    { word: "belligerent", definition: "Hostile and aggressive", sentence: "The ______ fan was removed from the stadium.", category: "General", difficulty: 2 },
    // Hard
    { word: "perspicacious", definition: "Having a ready insight into things; shrewd", sentence: "The ______ detective noticed what everyone else had missed.", category: "General", difficulty: 3 },
    { word: "surreptitious", definition: "Kept secret, especially because it would not be approved of", sentence: "She cast a ______ glance at his notes during the exam.", category: "General", difficulty: 3 },
    { word: "loquacious", definition: "Tending to talk a great deal", sentence: "The ______ salesman barely let the customer speak.", category: "General", difficulty: 3 },
    { word: "mellifluous", definition: "Sweet or musical; pleasant to hear", sentence: "Her ______ voice filled the concert hall effortlessly.", category: "General", difficulty: 3 },
    { word: "obsequious", definition: "Excessively compliant or deferential", sentence: "The ______ assistant agreed with everything the boss said.", category: "General", difficulty: 3 },
    { word: "ephemeral", definition: "Lasting for a very short time", sentence: "The beauty of cherry blossoms is intensely ______.", category: "General", difficulty: 3 },
    { word: "recalcitrant", definition: "Having an obstinately uncooperative attitude", sentence: "The ______ student refused every attempt at compromise.", category: "General", difficulty: 3 },
    { word: "verisimilitude", definition: "The appearance of being true or real", sentence: "The novel's ______ came from the author's firsthand experience.", category: "General", difficulty: 3 },
    { word: "circumlocution", definition: "The use of many words where fewer would do", sentence: "His answer was full of ______ and never addressed the question.", category: "General", difficulty: 3 },
    { word: "impecunious", definition: "Having little or no money", sentence: "The ______ artist lived in a tiny studio and ate simply.", category: "General", difficulty: 3 },
  ],

};

// ─── COUNTRIES & CAPITALS ────────────────────────────────────────────────────
const COUNTRIES_CAPITALS = [
  { country: "France", capital: "Paris", difficulty: 1 },
  { country: "Germany", capital: "Berlin", difficulty: 1 },
  { country: "Japan", capital: "Tokyo", difficulty: 1 },
  { country: "China", capital: "Beijing", difficulty: 1 },
  { country: "Australia", capital: "Canberra", difficulty: 1 },
  { country: "Canada", capital: "Ottawa", difficulty: 1 },
  { country: "Brazil", capital: "Brasilia", difficulty: 1 },
  { country: "Mexico", capital: "Mexico City", difficulty: 1 },
  { country: "India", capital: "New Delhi", difficulty: 1 },
  { country: "Russia", capital: "Moscow", difficulty: 1 },
  { country: "Italy", capital: "Rome", difficulty: 1 },
  { country: "Spain", capital: "Madrid", difficulty: 1 },
  { country: "Egypt", capital: "Cairo", difficulty: 1 },
  { country: "South Africa", capital: "Pretoria", difficulty: 1 },
  { country: "Argentina", capital: "Buenos Aires", difficulty: 1 },
  { country: "Greece", capital: "Athens", difficulty: 1 },
  { country: "Portugal", capital: "Lisbon", difficulty: 1 },
  { country: "Sweden", capital: "Stockholm", difficulty: 1 },
  { country: "Norway", capital: "Oslo", difficulty: 1 },
  { country: "Netherlands", capital: "Amsterdam", difficulty: 1 },
  { country: "Poland", capital: "Warsaw", difficulty: 1 },
  { country: "Turkey", capital: "Ankara", difficulty: 1 },
  { country: "Kenya", capital: "Nairobi", difficulty: 1 },
  { country: "Nigeria", capital: "Abuja", difficulty: 1 },
  { country: "Thailand", capital: "Bangkok", difficulty: 1 },
  { country: "Indonesia", capital: "Jakarta", difficulty: 1 },
  { country: "Pakistan", capital: "Islamabad", difficulty: 1 },
  { country: "Chile", capital: "Santiago", difficulty: 1 },
  { country: "Colombia", capital: "Bogota", difficulty: 1 },
  { country: "Afghanistan", capital: "Kabul", difficulty: 2 },
  { country: "Albania", capital: "Tirana", difficulty: 2 },
  { country: "Algeria", capital: "Algiers", difficulty: 2 },
  { country: "Angola", capital: "Luanda", difficulty: 2 },
  { country: "Armenia", capital: "Yerevan", difficulty: 2 },
  { country: "Austria", capital: "Vienna", difficulty: 2 },
  { country: "Azerbaijan", capital: "Baku", difficulty: 2 },
  { country: "Bangladesh", capital: "Dhaka", difficulty: 2 },
  { country: "Belarus", capital: "Minsk", difficulty: 2 },
  { country: "Belgium", capital: "Brussels", difficulty: 2 },
  { country: "Bolivia", capital: "Sucre", difficulty: 2 },
  { country: "Cambodia", capital: "Phnom Penh", difficulty: 2 },
  { country: "Cameroon", capital: "Yaounde", difficulty: 2 },
  { country: "Croatia", capital: "Zagreb", difficulty: 2 },
  { country: "Cuba", capital: "Havana", difficulty: 2 },
  { country: "Czech Republic", capital: "Prague", difficulty: 2 },
  { country: "Denmark", capital: "Copenhagen", difficulty: 2 },
  { country: "Ecuador", capital: "Quito", difficulty: 2 },
  { country: "Ethiopia", capital: "Addis Ababa", difficulty: 2 },
  { country: "Finland", capital: "Helsinki", difficulty: 2 },
  { country: "Ghana", capital: "Accra", difficulty: 2 },
  { country: "Hungary", capital: "Budapest", difficulty: 2 },
  { country: "Iceland", capital: "Reykjavik", difficulty: 2 },
  { country: "Iran", capital: "Tehran", difficulty: 2 },
  { country: "Iraq", capital: "Baghdad", difficulty: 2 },
  { country: "Ireland", capital: "Dublin", difficulty: 2 },
  { country: "Jordan", capital: "Amman", difficulty: 2 },
  { country: "Kazakhstan", capital: "Astana", difficulty: 2 },
  { country: "Libya", capital: "Tripoli", difficulty: 2 },
  { country: "Burkina Faso", capital: "Ouagadougou", difficulty: 3 },
  { country: "Kyrgyzstan", capital: "Bishkek", difficulty: 3 },
  { country: "Tajikistan", capital: "Dushanbe", difficulty: 3 },
  { country: "Turkmenistan", capital: "Ashgabat", difficulty: 3 },
  { country: "Uzbekistan", capital: "Tashkent", difficulty: 3 },
  { country: "Mozambique", capital: "Maputo", difficulty: 3 },
  { country: "Madagascar", capital: "Antananarivo", difficulty: 3 },
  { country: "Djibouti", capital: "Djibouti City", difficulty: 3 },
  { country: "Liechtenstein", capital: "Vaduz", difficulty: 3 },
  { country: "Moldova", capital: "Chisinau", difficulty: 3 },
  { country: "Montenegro", capital: "Podgorica", difficulty: 3 },
  { country: "Mauritania", capital: "Nouakchott", difficulty: 3 },
  { country: "Suriname", capital: "Paramaribo", difficulty: 3 },
  { country: "Vanuatu", capital: "Port Vila", difficulty: 3 },
  { country: "Eritrea", capital: "Asmara", difficulty: 3 },
  { country: "Comoros", capital: "Moroni", difficulty: 3 },
  { country: "Kiribati", capital: "South Tarawa", difficulty: 3 },
  { country: "Nauru", capital: "Yaren", difficulty: 3 },
  { country: "Palau", capital: "Ngerulmud", difficulty: 3 },
  { country: "Tuvalu", capital: "Funafuti", difficulty: 3 },
];

// ─── US STATES & CAPITALS ────────────────────────────────────────────────────
const STATES_CAPITALS = [
  { state: "California", capital: "Sacramento", difficulty: 1 },
  { state: "Texas", capital: "Austin", difficulty: 1 },
  { state: "Florida", capital: "Tallahassee", difficulty: 1 },
  { state: "New York", capital: "Albany", difficulty: 1 },
  { state: "Illinois", capital: "Springfield", difficulty: 1 },
  { state: "Ohio", capital: "Columbus", difficulty: 1 },
  { state: "Georgia", capital: "Atlanta", difficulty: 1 },
  { state: "Washington", capital: "Olympia", difficulty: 1 },
  { state: "Colorado", capital: "Denver", difficulty: 1 },
  { state: "Arizona", capital: "Phoenix", difficulty: 1 },
  { state: "Nevada", capital: "Carson City", difficulty: 1 },
  { state: "Oregon", capital: "Salem", difficulty: 1 },
  { state: "Tennessee", capital: "Nashville", difficulty: 1 },
  { state: "Virginia", capital: "Richmond", difficulty: 1 },
  { state: "Massachusetts", capital: "Boston", difficulty: 1 },
  { state: "Michigan", capital: "Lansing", difficulty: 1 },
  { state: "Louisiana", capital: "Baton Rouge", difficulty: 1 },
  { state: "Hawaii", capital: "Honolulu", difficulty: 1 },
  { state: "Alaska", capital: "Juneau", difficulty: 1 },
  { state: "Minnesota", capital: "Saint Paul", difficulty: 1 },
  { state: "Alabama", capital: "Montgomery", difficulty: 2 },
  { state: "Arkansas", capital: "Little Rock", difficulty: 2 },
  { state: "Connecticut", capital: "Hartford", difficulty: 2 },
  { state: "Delaware", capital: "Dover", difficulty: 2 },
  { state: "Idaho", capital: "Boise", difficulty: 2 },
  { state: "Indiana", capital: "Indianapolis", difficulty: 2 },
  { state: "Iowa", capital: "Des Moines", difficulty: 2 },
  { state: "Kansas", capital: "Topeka", difficulty: 2 },
  { state: "Kentucky", capital: "Frankfort", difficulty: 2 },
  { state: "Maine", capital: "Augusta", difficulty: 2 },
  { state: "Maryland", capital: "Annapolis", difficulty: 2 },
  { state: "Mississippi", capital: "Jackson", difficulty: 2 },
  { state: "Missouri", capital: "Jefferson City", difficulty: 2 },
  { state: "Montana", capital: "Helena", difficulty: 2 },
  { state: "Nebraska", capital: "Lincoln", difficulty: 2 },
  { state: "New Hampshire", capital: "Concord", difficulty: 2 },
  { state: "New Jersey", capital: "Trenton", difficulty: 2 },
  { state: "New Mexico", capital: "Santa Fe", difficulty: 2 },
  { state: "North Carolina", capital: "Raleigh", difficulty: 2 },
  { state: "Oklahoma", capital: "Oklahoma City", difficulty: 2 },
  { state: "North Dakota", capital: "Bismarck", difficulty: 3 },
  { state: "Pennsylvania", capital: "Harrisburg", difficulty: 3 },
  { state: "Rhode Island", capital: "Providence", difficulty: 3 },
  { state: "South Carolina", capital: "Columbia", difficulty: 3 },
  { state: "South Dakota", capital: "Pierre", difficulty: 3 },
  { state: "Utah", capital: "Salt Lake City", difficulty: 3 },
  { state: "Vermont", capital: "Montpelier", difficulty: 3 },
  { state: "West Virginia", capital: "Charleston", difficulty: 3 },
  { state: "Wisconsin", capital: "Madison", difficulty: 3 },
  { state: "Wyoming", capital: "Cheyenne", difficulty: 3 },
];

// ─── FLATTEN ALL STANDARD WORDS ───────────────────────────────────────────────
const ALL_WORDS = Object.entries(WORD_LIBRARY).flatMap(([catId, words]) =>
  words.map(w => ({ ...w, catId }))
);
